name: Build Release

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  VERSION: v0.3

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        shell: powershell
        run: |
          pip install -r requirements.txt

      - name: Build EXE
        shell: powershell
        run: |
          pyinstaller server.py `
            --onefile `
            --noconsole `
            --clean `
            --name "FB_server"

      - name: Create Release Folder
        shell: powershell
        run: |
          $releaseFolder = "FB自动活跃_${{ env.VERSION }}"

          mkdir $releaseFolder

          copy ".\dist\FB_server.exe" "$releaseFolder\"

          xcopy ".\WS Browser Bridge" "$releaseFolder\浏览器插件\" /E /I /Y

      - name: Zip Release
        shell: powershell
        run: |
          Compress-Archive `
          -Path "FB自动活跃_${{ env.VERSION }}" `
          -DestinationPath "FB自动活跃_${{ env.VERSION }}.zip"

      - name: Recreate Tag
        shell: powershell
        run: |
          git tag -d ${{ env.VERSION }} 2>$null
          git push origin :refs/tags/${{ env.VERSION }} 2>$null

          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          files: |
            FB自动活跃_${{ env.VERSION }}.zip